In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

In [2]:
df_merged_no_hol = pd.read_csv('no_hol_v2_edited.csv')
df_2018s2 = pd.read_csv('2018_2_no_exam.csv')
df_2019s1 = pd.read_csv('2019_1.csv')
df_closed = pd.read_csv('closed_semester.csv')

frames = [df_2018s2, df_2019s1]
joined = pd.concat(frames)
df = joined[joined['Station_depart.'] == '12 CU Terrace']
df

,Date,regist_dt_ICT,start_dt_ICT,end_dt_ICT,Customer_ID,Station_depart.,Station_dest.
49,7/1/2019,8:37:18,NaN,NaN,CP#0R1Y7,12 CU Terrace,02 Economics
50,7/1/2019,7:01:03,NaN,NaN,CP#0S9Z5,12 CU Terrace,03 Sala Prakeaw
51,7/1/2019,12:33:48,12:38:34,12:45:12,CP#0RPP9,12 CU Terrace,03 Sala Prakeaw
52,7/1/2019,8:44:00,9:02:11,9:08:28,CP#0PFV4,12 CU Terrace,04 Engineering
53,7/1/2019,8:50:49,8:51:18,8:58:37,CP#0PVP6,12 CU Terrace,04 Engineering
...,...,...,...,...,...,...,...
5796,30/9/2019,12:36:30,12:37:18,12:43:56,CP#0T9M5,12 CU Terrace,18 Art and Culture
5797,30/9/2019,12:45:55,NaN,NaN,CP#0WLR2,12 CU Terrace,18 Art and Culture
5798,30/9/2019,7:36:23,7:53:28,8:00:44,CP#0WHL8,12 CU Terrace,19 Pharmaceutical Science
5799,30/9/2019,12:22:00,12:27:09,12:32:12,CP#0S7J6,12 CU Terrace,19 Pharmaceutical Science
5846,30/9/2019,12:56:06,12:57:21,13:00:03,CP#0WMX2,12 CU Terrace,12 CU Terrace

In [3]:
mon_merged = ['7/1/2019', '14/1/2019', '21/1/2019', '28/1/2019', '4/2/2019', '11/2/2019', '18/2/2019', '25/2/2019', '4/3/2019', '11/3/2019', '18/3/2019', '25/3/2019', '1/4/2019', '8/4/2019', '15/4/2019', '22/4/2019', '29/4/2019', '6/5/2019', '13/5/2019', '20/5/2019', '27/5/2019', '10/6/2019', '17/6/2019', '24/6/2019', '1/7/2019', '8/7/2019', '15/7/2019', '22/7/2019', '5/8/2019', '12/8/2019', '19/8/2019', '26/8/2019', '2/9/2019', '9/9/2019', '16/9/2019', '23/9/2019', '30/9/2019']
tue_merged = ['1/1/2019', '8/1/2019', '15/1/2019', '22/1/2019', '29/1/2019', '5/2/2019', '12/2/2019', '26/2/2019', '5/3/2019', '12/3/2019', '19/3/2019', '26/3/2019', '2/4/2019', '9/4/2019', '16/4/2019', '23/4/2019', '30/4/2019', '7/5/2019', '14/5/2019', '21/5/2019', '28/5/2019', '4/6/2019', '11/6/2019', '18/6/2019', '25/6/2019', '2/7/2019', '9/7/2019', '23/7/2019', '30/7/2019', '6/8/2019', '13/8/2019', '20/8/2019', '27/8/2019', '3/9/2019', '10/9/2019', '17/9/2019', '24/9/2019']
wed_merged = ['2/1/2019', '9/1/2019', '16/1/2019', '23/1/2019', '30/1/2019', '6/2/2019', '13/2/2019', '20/2/2019', '27/2/2019', '6/3/2019', '13/3/2019', '20/3/2019', '27/3/2019', '3/4/2019', '10/4/2019', '17/4/2019', '24/4/2019', '1/5/2019', '8/5/2019', '15/5/2019', '22/5/2019', '29/5/2019', '5/6/2019', '12/6/2019', '19/6/2019', '26/6/2019', '3/7/2019', '10/7/2019', '24/7/2019', '31/7/2019', '7/8/2019', '14/8/2019', '21/8/2019', '28/8/2019', '4/9/2019', '11/9/2019', '18/9/2019', '25/9/2019']
thu_merged = ['3/1/2019', '10/1/2019', '17/1/2019', '24/1/2019', '31/1/2019', '7/2/2019', '14/2/2019', '21/2/2019', '28/2/2019', '7/3/2019', '14/3/2019', '21/3/2019', '28/3/2019', '4/4/2019', '11/4/2019', '18/4/2019', '25/4/2019', '2/5/2019', '9/5/2019', '16/5/2019', '23/5/2019', '30/5/2019', '6/6/2019', '13/6/2019', '20/6/2019', '27/6/2019', '4/7/2019', '11/7/2019', '18/7/2019', '25/7/2019', '1/8/2019', '8/8/2019', '15/8/2019', '22/8/2019', '29/8/2019', '5/9/2019', '12/9/2019', '19/9/2019', '26/9/2019']
fri_merged = ['4/1/2019', '11/1/2019', '18/1/2019', '25/1/2019', '1/2/2019', '8/2/2019', '15/2/2019', '22/2/2019', '1/3/2019', '8/3/2019', '15/3/2019', '22/3/2019', '29/3/2019', '5/4/2019', '12/4/2019', '19/4/2019', '26/4/2019', '3/5/2019', '10/5/2019', '17/5/2019', '24/5/2019', '31/5/2019', '7/6/2019', '14/6/2019', '21/6/2019', '28/6/2019', '5/7/2019', '12/7/2019', '19/7/2019', '26/7/2019', '2/8/2019', '9/8/2019', '16/8/2019', '23/8/2019', '30/8/2019', '6/9/2019', '13/9/2019', '20/9/2019', '27/9/2019']
sat_merged = ['5/1/2019', '22/6/2019']

mon_merged = pd.to_datetime(mon_merged, dayfirst=True)
tue_merged = pd.to_datetime(tue_merged, dayfirst=True)
wed_merged = pd.to_datetime(wed_merged, dayfirst=True)
thu_merged = pd.to_datetime(thu_merged, dayfirst=True)
fri_merged = pd.to_datetime(fri_merged, dayfirst=True)

# month = []
# for slot in train['Date']:
#     (d, m, y) = slot.split('/')
#     m = int(m)
#     if (m == 1):
#         month.append('1-Jan')
#     elif (m == 2):
#         month.append('2-Feb')
#     elif (m == 3):
#         month.append('3-Mar')
#     elif (m == 4):
#         month.append('4-Apr')
#     elif (m == 5):
#         month.append('5-May')
#     elif (m == 6):
#         month.append('6-Jun')
#     elif (m == 7):
#         month.append('7-Jul')
#     elif (m == 8):
#         month.append('8-Aug')
#     elif (m == 9):
#         month.append('9-Sep')
# train['Month'] = month

In [4]:
start = 7
stop = 21.5

def fill_missing(df, df_main, type):
    date = list(dict.fromkeys(df_main['Date']))
    
    if (type == True):
        oper_time = list(np.arange(start, stop, 0.5))
    else:
        oper_time = list(np.arange(start, stop))
    timestamp_all = []

    for each in date:
        each = str(each)
        each = each[0:11]
        for h in oper_time:
            (d, m, y) = each.split('/')
            d, m, y, hh = int(d), int(m), int(y), int(h)
            if (((h*10)%10) == 5):
                timestamp = pd.Timestamp(year=y, month=m, day=d, hour=hh, minute=30)
            else:
                timestamp = pd.Timestamp(year=y, month=m, day=d, hour=hh)
            timestamp_all.append(timestamp)

    timestamp_fill = list(set(timestamp_all) - set((list(dict.fromkeys(df['Timestamp'])))))

    demand_fill = []
    demand_fill = [0] * len(timestamp_fill)

    data_fill = {'Timestamp': timestamp_fill, 'Demand': demand_fill}    
    df_od_fill = pd.DataFrame(data_fill)
    df_od_fill = df_od_fill.sort_values('Timestamp')
    df_od_fill = df_od_fill.reset_index(drop=True)
    
    df, backup = group_by_time(df)
    
    df = df.append(df_od_fill)
    df = df.sort_values('Timestamp')
    df = df.reset_index(drop=True)
    
    return df

def group_by_time(df):
    df = df.groupby('Timestamp').sum()
    backup = df
    df = df.reset_index()
    
    return df, backup

def create_window(df, type):
    converted_regist = []

    for slot in df['regist_dt_ICT']:
        (h, m, s) = slot.split(':')
        if (type == True):
            if (int(m) >= 30):
                time = int(h) + 0.5
            else:
                time = int(h)
        else:
            time = int(h)
        converted_regist.append(time)    

    df['Converted_Regist'] = converted_regist
    
    df = df[df['Converted_Regist'] >= start]
    df = df[df['Converted_Regist'] < stop]
    
    return df

def create_timestamp(df, type): 
    df['DateTime'] = df[df.columns[0:2]].apply(lambda x : '/' .join(x.astype(str)),axis=1)
    df['DateTime'] = df['DateTime'].str.replace(":", "/")
    
    timestamp_converted = []
    
    for slot in df['DateTime']:
        (d, m, y, hh, mm, ss) = slot.split('/')
        d, m, y, hh, mm = int(d), int(m), int(y), int(hh), int(mm)
        if (type == True):
            if (mm >= 30):
                timestamp = pd.Timestamp(year=y, month=m, day=d, hour=hh, minute=30)
            else:
                timestamp = pd.Timestamp(year=y, month=m, day=d, hour=hh)
        else:
            timestamp = pd.Timestamp(year=y, month=m, day=d, hour=hh)
        timestamp_converted.append(timestamp)
        
    df['Timestamp'] = timestamp_converted
    
    df = df.drop('DateTime', axis=1)
    
    return df

def add_dds(df, station):
    date = []
    for each in df['Timestamp']:
        each = str(each)
        each = each[0:10]
        date.append(each)
        
    df['Date'] = date
    df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

    day = []
    for slot in train['Date']:
        if slot in mon_merged:
            day.append('1')
        if slot in tue_merged:
            day.append('2')
        if slot in wed_merged:
            day.append('3')
        if slot in thu_merged:
            day.append('4')
        if slot in fri_merged:
            day.append('5')
            
    train['Day'] = day
    
    destination = []
    destination = [station] * len(df)
    df['Destination'] = destination
    
    return df

def add_demand(df):
    demand = []
    demand = [1] * len(df)
    df['Demand'] = demand
    
    return df

def extract_regist(df):
    converted_regist = []
    
    for each in df['Timestamp']:
        each = str(each)
        hour = int(each[11:13])
        converted_regist.append(hour)    

    df['Converted_Regist'] = converted_regist
    
    return df

In [5]:
# df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
# df.set_index('Date', inplace=True)
# df_train = df
# df = df.reset_index()
# df

# df_train = df_train_clone = df[:'2019-04-30']
# df_test = df_test_clone = df['2019-05-01':'2019-05-23']
# df_test = df_test_clone = df['2019-04-01':'2019-04-30']
# df_train2 = df_train_clone2 = df['2019-08-13':'2019-09-20']
# df_test2 = df_test_clone2 = df['2019-09-23':'2019-09-30']
# df_test_clone = df_test_clone.reset_index()
# df_train_clone2 = df_train_clone2.reset_index()
# df_test_clone2 = df_test_clone2.reset_index()
# df_train_clone

In [6]:
all_destination = date = list(dict.fromkeys(df['Station_dest.']))
df_with_timestamp = create_timestamp(df, False)
df = add_demand(df)
template = {'Timestamp', 'Demand', 'Date', 'Day', 'Converted_Regist'}    
df_joined = pd.DataFrame(template)

for station in all_destination:
    df_od = df[df['Station_dest.'] == station]
    df_od = create_timestamp(df_od, False)
#     train_framed = create_window(df_od, False)
    train, backup_train = group_by_time(df_od)
    train = train_clone = fill_missing(train, df_with_timestamp, False)
    train = add_dds(train, station)
    train = extract_regist(train)
    print(train)

               Timestamp  Demand       Date Day   Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  02 Economics
1    2019-01-07 08:00:00       1 2019-01-07   1  02 Economics
2    2019-01-07 09:00:00       0 2019-01-07   1  02 Economics
3    2019-01-07 10:00:00       0 2019-01-07   1  02 Economics
4    2019-01-07 11:00:00       0 2019-01-07   1  02 Economics
...                  ...     ...        ...  ..           ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  02 Economics
1646 2019-09-30 18:00:00       0 2019-09-30   1  02 Economics
1647 2019-09-30 19:00:00       0 2019-09-30   1  02 Economics
1648 2019-09-30 20:00:00       0 2019-09-30   1  02 Economics
1649 2019-09-30 21:00:00       0 2019-09-30   1  02 Economics

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day      Destination  \
0    2019-01-07 07:00:00       1 2019-01-07   1  03 Sala Prakeaw
1    2019-01-07 08:00:00       0 2019-01-07   1  03 Sala Prakeaw
2    2019-01-07 09:00:00       0 2019-01-07   1  03 Sala Prakeaw
3    2019-01-07 10:00:00       0 2019-01-07   1  03 Sala Prakeaw
4    2019-01-07 11:00:00       0 2019-01-07   1  03 Sala Prakeaw
...                  ...     ...        ...  ..              ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  03 Sala Prakeaw
1646 2019-09-30 18:00:00       0 2019-09-30   1  03 Sala Prakeaw
1647 2019-09-30 19:00:00       0 2019-09-30   1  03 Sala Prakeaw
1648 2019-09-30 20:00:00       0 2019-09-30   1  03 Sala Prakeaw
1649 2019-09-30 21:00:00       0 2019-09-30   1  03 Sala Prakeaw

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day     Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  04 Engineering
1    2019-01-07 08:00:00       2 2019-01-07   1  04 Engineering
2    2019-01-07 09:00:00       0 2019-01-07   1  04 Engineering
3    2019-01-07 10:00:00       0 2019-01-07   1  04 Engineering
4    2019-01-07 11:00:00       1 2019-01-07   1  04 Engineering
...                  ...     ...        ...  ..             ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  04 Engineering
1646 2019-09-30 18:00:00       0 2019-09-30   1  04 Engineering
1647 2019-09-30 19:00:00       0 2019-09-30   1  04 Engineering
1648 2019-09-30 20:00:00       0 2019-09-30   1  04 Engineering
1649 2019-09-30 21:00:00       0 2019-09-30   1  04 Engineering

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day              Destination  \
0    2019-01-07 07:00:00       1 2019-01-07   1  11 BTS-National stadium
1    2019-01-07 08:00:00       0 2019-01-07   1  11 BTS-National stadium
2    2019-01-07 09:00:00       0 2019-01-07   1  11 BTS-National stadium
3    2019-01-07 10:00:00       0 2019-01-07   1  11 BTS-National stadium
4    2019-01-07 11:00:00       0 2019-01-07   1  11 BTS-National stadium
...                  ...     ...        ...  ..                      ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  11 BTS-National stadium
1646 2019-09-30 18:00:00       0 2019-09-30   1  11 BTS-National stadium
1647 2019-09-30 19:00:00       0 2019-09-30   1  11 BTS-National stadium
1648 2019-09-30 20:00:00       0 2019-09-30   1  11 BTS-National stadium
1649 2019-09-30 21:00:00       0 2019-09-30   1  11 BTS-National stadium

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day         Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  18 Art and Culture
1    2019-01-07 08:00:00       1 2019-01-07   1  18 Art and Culture
2    2019-01-07 09:00:00       0 2019-01-07   1  18 Art and Culture
3    2019-01-07 10:00:00       0 2019-01-07   1  18 Art and Culture
4    2019-01-07 11:00:00       0 2019-01-07   1  18 Art and Culture
...                  ...     ...        ...  ..                 ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  18 Art and Culture
1646 2019-09-30 18:00:00       0 2019-09-30   1  18 Art and Culture
1647 2019-09-30 19:00:00       0 2019-09-30   1  18 Art and Culture
1648 2019-09-30 20:00:00       0 2019-09-30   1  18 Art and Culture
1649 2019-09-30 21:00:00       0 2019-09-30   1  18 Art and Culture

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day             Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  21 Wittayakit Building
1    2019-01-07 08:00:00       0 2019-01-07   1  21 Wittayakit Building
2    2019-01-07 09:00:00       0 2019-01-07   1  21 Wittayakit Building
3    2019-01-07 10:00:00       0 2019-01-07   1  21 Wittayakit Building
4    2019-01-07 11:00:00       0 2019-01-07   1  21 Wittayakit Building
...                  ...     ...        ...  ..                     ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  21 Wittayakit Building
1646 2019-09-30 18:00:00       0 2019-09-30   1  21 Wittayakit Building
1647 2019-09-30 19:00:00       0 2019-09-30   1  21 Wittayakit Building
1648 2019-09-30 20:00:00       0 2019-09-30   1  21 Wittayakit Building
1649 2019-09-30 21:00:00       0 2019-09-30   1  21 Wittayakit Building

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day             Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  01 Exit to Cham square
1    2019-01-07 08:00:00       0 2019-01-07   1  01 Exit to Cham square
2    2019-01-07 09:00:00       0 2019-01-07   1  01 Exit to Cham square
3    2019-01-07 10:00:00       0 2019-01-07   1  01 Exit to Cham square
4    2019-01-07 11:00:00       0 2019-01-07   1  01 Exit to Cham square
...                  ...     ...        ...  ..                     ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  01 Exit to Cham square
1646 2019-09-30 18:00:00       0 2019-09-30   1  01 Exit to Cham square
1647 2019-09-30 19:00:00       0 2019-09-30   1  01 Exit to Cham square
1648 2019-09-30 20:00:00       0 2019-09-30   1  01 Exit to Cham square
1649 2019-09-30 21:00:00       0 2019-09-30   1  01 Exit to Cham square

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day            Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  20 Veterinary Science
1    2019-01-07 08:00:00       0 2019-01-07   1  20 Veterinary Science
2    2019-01-07 09:00:00       0 2019-01-07   1  20 Veterinary Science
3    2019-01-07 10:00:00       0 2019-01-07   1  20 Veterinary Science
4    2019-01-07 11:00:00       0 2019-01-07   1  20 Veterinary Science
...                  ...     ...        ...  ..                    ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  20 Veterinary Science
1646 2019-09-30 18:00:00       0 2019-09-30   1  20 Veterinary Science
1647 2019-09-30 19:00:00       0 2019-09-30   1  20 Veterinary Science
1648 2019-09-30 20:00:00       0 2019-09-30   1  20 Veterinary Science
1649 2019-09-30 21:00:00       0 2019-09-30   1  20 Veterinary Science

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]

               Timestamp  Demand       Date Day           Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  22 Siam Square Soi 8
1    2019-01-07 08:00:00       0 2019-01-07   1  22 Siam Square Soi 8
2    2019-01-07 09:00:00       0 2019-01-07   1  22 Siam Square Soi 8
3    2019-01-07 10:00:00       0 2019-01-07   1  22 Siam Square Soi 8
4    2019-01-07 11:00:00       0 2019-01-07   1  22 Siam Square Soi 8
...                  ...     ...        ...  ..                   ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  22 Siam Square Soi 8
1646 2019-09-30 18:00:00       0 2019-09-30   1  22 Siam Square Soi 8
1647 2019-09-30 19:00:00       0 2019-09-30   1  22 Siam Square Soi 8
1648 2019-09-30 20:00:00       0 2019-09-30   1  22 Siam Square Soi 8
1649 2019-09-30 21:00:00       0 2019-09-30   1  22 Siam Square Soi 8

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day Destination  Converted_Regist
0    2019-01-07 07:00:00       0 2019-01-07   1     05 Arts                 7
1    2019-01-07 08:00:00       0 2019-01-07   1     05 Arts                 8
2    2019-01-07 09:00:00       0 2019-01-07   1     05 Arts                 9
3    2019-01-07 10:00:00       0 2019-01-07   1     05 Arts                10
4    2019-01-07 11:00:00       0 2019-01-07   1     05 Arts                11
...                  ...     ...        ...  ..         ...               ...
1645 2019-09-30 17:00:00       0 2019-09-30   1     05 Arts                17
1646 2019-09-30 18:00:00       0 2019-09-30   1     05 Arts                18
1647 2019-09-30 19:00:00       0 2019-09-30   1     05 Arts                19
1648 2019-09-30 20:00:00       0 2019-09-30   1     05 Arts                20
1649 2019-09-30 21:00:00       0 2019-09-30   1     05 Arts                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day     Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  07 Chamchuri 5
1    2019-01-07 08:00:00       0 2019-01-07   1  07 Chamchuri 5
2    2019-01-07 09:00:00       0 2019-01-07   1  07 Chamchuri 5
3    2019-01-07 10:00:00       0 2019-01-07   1  07 Chamchuri 5
4    2019-01-07 11:00:00       0 2019-01-07   1  07 Chamchuri 5
...                  ...     ...        ...  ..             ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  07 Chamchuri 5
1646 2019-09-30 18:00:00       0 2019-09-30   1  07 Chamchuri 5
1647 2019-09-30 19:00:00       0 2019-09-30   1  07 Chamchuri 5
1648 2019-09-30 20:00:00       0 2019-09-30   1  07 Chamchuri 5
1649 2019-09-30 21:00:00       0 2019-09-30   1  07 Chamchuri 5

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day  Destination  Converted_Regist
0    2019-01-07 07:00:00       0 2019-01-07   1  15 U Center                 7
1    2019-01-07 08:00:00       0 2019-01-07   1  15 U Center                 8
2    2019-01-07 09:00:00       0 2019-01-07   1  15 U Center                 9
3    2019-01-07 10:00:00       0 2019-01-07   1  15 U Center                10
4    2019-01-07 11:00:00       0 2019-01-07   1  15 U Center                11
...                  ...     ...        ...  ..          ...               ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  15 U Center                17
1646 2019-09-30 18:00:00       0 2019-09-30   1  15 U Center                18
1647 2019-09-30 19:00:00       0 2019-09-30   1  15 U Center                19
1648 2019-09-30 20:00:00       0 2019-09-30   1  15 U Center                20
1649 2019-09-30 21:00:00       0 2019-09-30   1  15 U Center                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day         Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  17 Property office
1    2019-01-07 08:00:00       0 2019-01-07   1  17 Property office
2    2019-01-07 09:00:00       0 2019-01-07   1  17 Property office
3    2019-01-07 10:00:00       0 2019-01-07   1  17 Property office
4    2019-01-07 11:00:00       0 2019-01-07   1  17 Property office
...                  ...     ...        ...  ..                 ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  17 Property office
1646 2019-09-30 18:00:00       0 2019-09-30   1  17 Property office
1647 2019-09-30 19:00:00       0 2019-09-30   1  17 Property office
1648 2019-09-30 20:00:00       0 2019-09-30   1  17 Property office
1649 2019-09-30 21:00:00       0 2019-09-30   1  17 Property office

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day      Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  09 Chamchuri 10
1    2019-01-07 08:00:00       0 2019-01-07   1  09 Chamchuri 10
2    2019-01-07 09:00:00       0 2019-01-07   1  09 Chamchuri 10
3    2019-01-07 10:00:00       0 2019-01-07   1  09 Chamchuri 10
4    2019-01-07 11:00:00       0 2019-01-07   1  09 Chamchuri 10
...                  ...     ...        ...  ..              ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  09 Chamchuri 10
1646 2019-09-30 18:00:00       0 2019-09-30   1  09 Chamchuri 10
1647 2019-09-30 19:00:00       0 2019-09-30   1  09 Chamchuri 10
1648 2019-09-30 20:00:00       0 2019-09-30   1  09 Chamchuri 10
1649 2019-09-30 21:00:00       0 2019-09-30   1  09 Chamchuri 10

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day    Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  12 CU Terrace
1    2019-01-07 08:00:00       0 2019-01-07   1  12 CU Terrace
2    2019-01-07 09:00:00       0 2019-01-07   1  12 CU Terrace
3    2019-01-07 10:00:00       0 2019-01-07   1  12 CU Terrace
4    2019-01-07 11:00:00       0 2019-01-07   1  12 CU Terrace
...                  ...     ...        ...  ..            ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  12 CU Terrace
1646 2019-09-30 18:00:00       0 2019-09-30   1  12 CU Terrace
1647 2019-09-30 19:00:00       0 2019-09-30   1  12 CU Terrace
1648 2019-09-30 20:00:00       0 2019-09-30   1  12 CU Terrace
1649 2019-09-30 21:00:00       0 2019-09-30   1  12 CU Terrace

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day     Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  06 Chamchuri 9
1    2019-01-07 08:00:00       0 2019-01-07   1  06 Chamchuri 9
2    2019-01-07 09:00:00       0 2019-01-07   1  06 Chamchuri 9
3    2019-01-07 10:00:00       0 2019-01-07   1  06 Chamchuri 9
4    2019-01-07 11:00:00       0 2019-01-07   1  06 Chamchuri 9
...                  ...     ...        ...  ..             ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  06 Chamchuri 9
1646 2019-09-30 18:00:00       0 2019-09-30   1  06 Chamchuri 9
1647 2019-09-30 19:00:00       0 2019-09-30   1  06 Chamchuri 9
1648 2019-09-30 20:00:00       0 2019-09-30   1  06 Chamchuri 9
1649 2019-09-30 21:00:00       0 2019-09-30   1  06 Chamchuri 9

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]

               Timestamp  Demand       Date Day            Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  16 Communication Arts
1    2019-01-07 08:00:00       0 2019-01-07   1  16 Communication Arts
2    2019-01-07 09:00:00       0 2019-01-07   1  16 Communication Arts
3    2019-01-07 10:00:00       0 2019-01-07   1  16 Communication Arts
4    2019-01-07 11:00:00       0 2019-01-07   1  16 Communication Arts
...                  ...     ...        ...  ..                    ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  16 Communication Arts
1646 2019-09-30 18:00:00       0 2019-09-30   1  16 Communication Arts
1647 2019-09-30 19:00:00       0 2019-09-30   1  16 Communication Arts
1648 2019-09-30 20:00:00       0 2019-09-30   1  16 Communication Arts
1649 2019-09-30 21:00:00       0 2019-09-30   1  16 Communication Arts

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day  Destination  Converted_Regist
0    2019-01-07 07:00:00       0 2019-01-07   1  14 I'm Park                 7
1    2019-01-07 08:00:00       0 2019-01-07   1  14 I'm Park                 8
2    2019-01-07 09:00:00       0 2019-01-07   1  14 I'm Park                 9
3    2019-01-07 10:00:00       0 2019-01-07   1  14 I'm Park                10
4    2019-01-07 11:00:00       0 2019-01-07   1  14 I'm Park                11
...                  ...     ...        ...  ..          ...               ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  14 I'm Park                17
1646 2019-09-30 18:00:00       0 2019-09-30   1  14 I'm Park                18
1647 2019-09-30 19:00:00       0 2019-09-30   1  14 I'm Park                19
1648 2019-09-30 20:00:00       0 2019-09-30   1  14 I'm Park                20
1649 2019-09-30 21:00:00       0 2019-09-30   1  14 I'm Park                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day        Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  08 Witthaya Nives
1    2019-01-07 08:00:00       0 2019-01-07   1  08 Witthaya Nives
2    2019-01-07 09:00:00       0 2019-01-07   1  08 Witthaya Nives
3    2019-01-07 10:00:00       0 2019-01-07   1  08 Witthaya Nives
4    2019-01-07 11:00:00       0 2019-01-07   1  08 Witthaya Nives
...                  ...     ...        ...  ..                ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  08 Witthaya Nives
1646 2019-09-30 18:00:00       0 2019-09-30   1  08 Witthaya Nives
1647 2019-09-30 19:00:00       0 2019-09-30   1  08 Witthaya Nives
1648 2019-09-30 20:00:00       0 2019-09-30   1  08 Witthaya Nives
1649 2019-09-30 21:00:00       0 2019-09-30   1  08 Witthaya Nives

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day                Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  19 Pharmaceutical Science
1    2019-01-07 08:00:00       0 2019-01-07   1  19 Pharmaceutical Science
2    2019-01-07 09:00:00       0 2019-01-07   1  19 Pharmaceutical Science
3    2019-01-07 10:00:00       0 2019-01-07   1  19 Pharmaceutical Science
4    2019-01-07 11:00:00       0 2019-01-07   1  19 Pharmaceutical Science
...                  ...     ...        ...  ..                        ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  19 Pharmaceutical Science
1646 2019-09-30 18:00:00       0 2019-09-30   1  19 Pharmaceutical Science
1647 2019-09-30 19:00:00       0 2019-09-30   1  19 Pharmaceutical Science
1648 2019-09-30 20:00:00       0 2019-09-30   1  19 Pharmaceutical Science
1649 2019-09-30 21:00:00       0 2019-09-30   1  19 Pharmaceutical Science

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]
               Timestamp  Demand       Date Day     Destination  \
0    2019-01-07 07:00:00       0 2019-01-07   1  10 Chulapat 14
1    2019-01-07 08:00:00       0 2019-01-07   1  10 Chulapat 14
2    2019-01-07 09:00:00       0 2019-01-07   1  10 Chulapat 14
3    2019-01-07 10:00:00       0 2019-01-07   1  10 Chulapat 14
4    2019-01-07 11:00:00       0 2019-01-07   1  10 Chulapat 14
...                  ...     ...        ...  ..             ...
1645 2019-09-30 17:00:00       0 2019-09-30   1  10 Chulapat 14
1646 2019-09-30 18:00:00       0 2019-09-30   1  10 Chulapat 14
1647 2019-09-30 19:00:00       0 2019-09-30   1  10 Chulapat 14
1648 2019-09-30 20:00:00       0 2019-09-30   1  10 Chulapat 14
1649 2019-09-30 21:00:00       0 2019-09-30   1  10 Chulapat 14

      Converted_Regist
0                    7
1                    8
2                    9
3                   10
4                   11
...                ...
1645                17
1646                18
1647                19
1648                20
1649                21

[1650 rows x 6 columns]

In [ ]:
df2 = create_timestamp(df, False)
train_framed = create_window(df2, False)
train, backup_train = group_by_time(train_framed)
train = train_clone = fill_missing(train, df_with_timestamp, False)
train = add_date_and_day(train)
train
# df_mod = df[['']]

In [ ]:
df1 = train[['Day', 'Converted_Regist', 'Demand']]
df1.head(30)

In [ ]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

le = LabelEncoder()
X_2 = df1.apply(le.fit_transform)
X_2.head(30)

In [ ]:
onehotlabels

In [ ]:
y = df1['Demand']
X = df1.drop('Demand', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 100)

In [ ]:
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)

In [ ]:
fi = pd.Series(model.feature_importances_, index=X_train.columns).sort_values()
fi

In [ ]:
y_predicted = model.predict(X_test)
print('Accuracy {:.5f}'.format(model.score(X_test, y_test)))
print(classification_report(y_predicted, y_test))
cnf_matrix = metrics.confusion_matrix(y_test, y_predicted)
cnf_matrix

In [ ]:
import graphviz

dot_data = tree.export_graphviz(model, out_file=None, 
                                feature_names=X_train.columns,  
                                class_names=y_train.name,  
                                filled=True,  
                                special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render('classification tree')

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0) 

regressor.fit(X_train, y_train)

In [ ]:
y_predicted = model.predict(X_test)
print('Accuracy {:.5f}'.format(model.score(X_test, y_test)))
print(classification_report(y_predicted, y_test))
cnf_matrix = metrics.confusion_matrix(y_test, y_predicted)
cnf_matrix

In [ ]:
from sklearn.metrics import roc_auc_score
rf_probs = model.predict_proba(y_test)[:, 1]
roc_value = roc_auc_score(y_test, rf_probs)